### PR TITLE
add-secure-context-headers (re: WebAssembly / SharedArrayBuffer)

### PR DESCRIPTION
**Pull request by ltomes**
@koa/cors just had support for secure-context added: https://github.com/koajs/cors/commit/134ec9b54b18565cf8bba8c5e6b6639d7d7e43a3

Details on why this is needed: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer/Planned_changes

This pr updates lwsjs to also support secure-context.

### CODE REVIEW

**Comment by 75lb** [comment]
interesting, thanks! Is there any reason the `secureContext` option [added to koa](https://github.com/koajs/cors/pull/82) supports `same-origin` but not `same-origin-allow-popups`? 

```
Cross-Origin-Opener-Policy: unsafe-none
Cross-Origin-Opener-Policy: same-origin-allow-popups
Cross-Origin-Opener-Policy: same-origin
```

**Comment by ltomes** [comment]
Yeah maybe I should open a pr for a wider opener policy. I added the headers I would need to use `SharedArrayBuffer`, and didn't think much about other use cases like enabling popups.

**Comment by 75lb** [comment]
released in lws-cors@4.1.1..

Please upgrade your local-web-server and run this:

```
$ ws --cors.opener-policy same-origin --cors.embedder-policy require-corp
```

Let me know if there's anything, else.. 👍

**Comment by ltomes** [comment]
> released in lws-cors@4.1.1..
> 
> Please upgrade your local-web-server and run this:
> 
> ```
> $ ws --cors.opener-policy same-origin --cors.embedder-policy require-corp
> ```
> 
> Let me know if there's anything, else.. 👍

I installed `local-web-server@5.2.0`, when ran with: `ws --cors.opener-policy same-origin --cors.embedder-policy require-corp`

I am not seeing any cors headers:
```
└─$ curl http://172.29.126.125:8000 --head
HTTP/1.1 200 OK
Vary: Origin
Accept-Ranges: bytes
Content-Length: 9695
Last-Modified: Thu, 10 Mar 2022 22:52:48 GMT
Cache-Control: max-age=0
Content-Type: text/html; charset=utf-8
ETag: W/"25df-17f7608e31b"
Date: Sun, 13 Mar 2022 19:36:09 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

I will try to look into this more this evening.

**Comment by 75lb** [comment]
CORS headers are only added when an `Origin` header is present in the request.. try this.. 

```
$ curl http://172.29.126.125:8000 --head -H 'Origin: https://something.com'
```

**Comment by ltomes** [comment]
Good callout/thanks for the command my `curl` skills are not strong. That command returns as expected, I think this is working. I'll run some webassembly against this later tonight but I'm expecting `SharedArrayBuffer` to function as expected.

```
└─$ curl http://172.29.126.125:8000 --head -H 'Origin: https://something.com'
HTTP/1.1 200 OK
Vary: Origin
Access-Control-Allow-Origin: https://something.com
Accept-Ranges: bytes
Content-Length: 9695
ETag: W/"25df-17f7608e31b"
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
Date: Sun, 13 Mar 2022 19:46:53 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by ltomes** [comment]
Ok, I had some time to look at this. 
This is a really weird implementation for COOP and COEP compared to other cross origin concerns. 

The bottom line is, the opener policy and embedder policy needs to be present on the _initial_ page load request, which is likely not cross origin by default.

Meaning proper (bare bones) implementation in node looks like this:
```
import { createServer } from 'http'
import { readFile } from 'fs'
const hostname = '127.0.0.1';
const port = 1337;
const index = await readFile('./index.html', (err, data) => data);
createServer(function(req, res){
  readFile('./index.html',function (err, data){
      res.writeHead(200, {
        'Content-Type': 'text/html',
        'Content-Type': 'text/html; charset=utf8',
        'Cross-Origin-Opener-Policy': 'same-origin',
        'Cross-Origin-Embedder-Policy': 'require-corp',
        'Content-Length':data.length}
      );
      res.write( data);
      res.end();
  });
}).listen(port, hostname);
```

So as a quick test you can:
```
import { createServer } from 'http'
import { readFile } from 'fs'
const hostname = '127.0.0.1';
const port = 1337;
const index = await readFile('./index.html', (err, data) => data);
createServer(function(req, res){
    res.writeHead(200, {
      'Content-Type': 'text/html',
      'Content-Type': 'text/html; charset=utf8',
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
      'Content-Length':data.length}
    );
    res.write('');
    res.end();
}).listen(port, hostname);
```

// Visit 127.0.0.1:1337, assert SharedArrayBuffer is defined on the page:
image


```
import { createServer } from 'http'
import { readFile } from 'fs'
const hostname = '127.0.0.1';
const port = 1337;
const index = await readFile('./index.html', (err, data) => data);
createServer(function(req, res){
    res.writeHead(200, {
      'Content-Type': 'text/html',
      'Content-Type': 'text/html; charset=utf8',
      'Content-Length':data.length}
    );
    res.write('');
    res.end();
}).listen(port, hostname);
```
// Visit 127.0.0.1:1337, assert SharedArrayBuffer is defined on the page:
image

So all that is to say, these new flags should be set on requests that are not cross origin (but only when the flags are enabled, as there is risk of spectre / meltdown). Apologies if the wall of text above is annoying, I find it's easier to explain my perspective by showing the work.

**Comment by 75lb** [comment]
thanks for the extra checks and confirmation 👍  .. released in `lws-cors@4.1.2`

**Comment by ltomes** [comment]
Thanks for getting these changes in, web assembly is running as expected in `ws` now.
If anyone is looking at this in the future, make sure to run your server as `http2` as well, so [self.crossOriginIsolated](https://developer.mozilla.org/docs/Web/API/WindowOrWorkerGlobalScope/crossOriginIsolated) is properly set/the CORS policies are respected: `ws --cors.opener-policy same-origin --cors.embedder-policy require-corp --http2`

**Pull request merged**
